import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import Footer from "../components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Flam ",
  description: "Generated by create next app, created by Lakshya",
  icons: [
    { rel: "icon", url: "/site-icon.ico" },
    { rel: "shortcut icon", url: "/site-icon.ico" },
    { rel: "apple-touch-icon", url: "/site-icon.ico" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white flex flex-col min-h-screen`}
      >
        <Navbar />
        <main className="bg-black text-white flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
